package com.reactorx.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

@Entity
@Table(name = "media") // Optional: Specify table name if different from class name
@Data // Lombok annotation for getters, setters, toString, equals, hashCode
@NoArgsConstructor // Lombok annotation for no-args constructor
@AllArgsConstructor // Lombok annotation for all-args constructor
public class Media {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 50) // e.g., "image", "video"
    private String type;

    @Column(nullable = false, length = 1024) // Store the URL or path
    private String src;

    // Many media items can belong to one product
    @ManyToOne(fetch = FetchType.LAZY) // Lazy fetch is generally recommended
    @JoinColumn(name = "product_id", nullable = false) // Foreign key column in the 'media' table
    private Product product;

    // --- Constructors (Generated by Lombok) ---

    // --- Getters and Setters (Generated by Lombok's @Data) ---

    // --- equals(), hashCode(), toString() (Generated by Lombok's @Data) ---
}
